config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resources :comments, only: [:create, :destroy, :edit, :update]
  resources :posts, only: [:index, :show, :create, :destroy, :edit, :update] do
    member do
      post '/like', to: "likes#create", as: "like"
      delete '/like', to: "likes#destroy", as: "unlike"
    end
  end
  
  post '/follows', to: "follows#create", as: "follow"
  delete '/follows', to: "follows#destroy", as: "unfollow"

  get '/profile/:id', to: "users#show", as: "user"
  get '/profile/:id/following', to: "users#following", as: "following"
  get '/profile/:id/followers', to: "users#followers", as: "followers"
  post '/users/search', to: "users#search", as: :search
  get '/users/search', to: "users#search"

  devise_for :users, :controllers => { registrations: 'registrations' }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

  has_many :posts
  has_many :likes

  acts_as_followable
  acts_as_follower
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # load_and_authorize_resource
  before_action :set_user, only: [:show, :following, :followers]
  
  def show
    @posts = @user.posts
    @following = @user.following_users.limit(5)
    @followers = @user.followers_by_type('User').limit(5)
  end

  def following
    @following = @user.following_users
  end

  def followers
    @followers = @user.followers_by_type('User')
  end

  def search
    @user = current_user
    @query = User.ransack(params[:q])
    @users = @query.result(distinct: true)
  end

  private

    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/followers.html.erb
<div class="row">
    <div class="col s12 m12 l4">
      <%= render 'shared/user-info' %>
    </div>
    <div class="col l1"></div>
    <div class="col l7 page-content">
      <h4 class="follow-title">Followers</h4>
      <%= render 'shared/list-user', users: @followers %>
    </div>
  </div>

app/views/users/followings.html.erb
<div class="row">
    <div class="col s12 m12 l4">
      <%= render 'shared/user-info' %>
    </div>
    <div class="col l1"></div>
    <div class="col l7 page-content">
      <h4 class="follow-title">Following</h4>
      <%= render 'shared/list-user', users: @following %>
    </div>
  </div>

app/views/users/search.html.erb
<div class="row">
    <div class="col s12 m12 l4">
        <%= render 'shared/user-info' %>
    </div>
    <div class="col l1"></div>
    <div class="col l7 page-content">
      <h4 class="follow-title">People</h4>
      <%= render 'shared/list-user', users: @users %>
    </div>
  </div>

app/views/users/show.html.erb
<div class="row">
    <div class="col s12 m12 l3">
      <div class="row">
        <%= render 'shared/user-info' %>
      </div>
  
      <div class="row">
        <div class="card">
          <div class="card-tabs">
            <ul class="tabs">
              <li class="tab">
                <a class="active" href="#followers">Followers</a>
              </li>
              <li class="tab">
                <a href="#following">Following</a>
              </li>
            </ul>
          </div>
          <div class="card-content grey lighten-4">
            <div id="followers">
              <ul class="collection">
                <% @followers.each do |f| %>
                  <li class="collection-item avatar">
                    <img src="<%= f.avatar.url %>" class="circle">
                    <span class="title">
                      <%= link_to truncate(f.name, length: 15), user_path(f) %>
                    </span>
                    <p>
                      <%= truncate(f.description, length: 15) %>
                    </p>
                  </li>
                <% end %>
              </ul>
              <%= link_to "See all followers", followers_path(@user) %>
            </div>
            <div id="following">
              <ul class="collection">
                <% @following.each do |f| %>
                  <li class="collection-item avatar">
                    <img src="<%= f.avatar.url %>" class="circle">
                    <span class="title"><%= link_to f.name, user_path(f) %></span>
                    <p>
                      <%= truncate(f.description, length: 15) %>
                    </p>
                  </li>
                <% end %>
              </ul>
              <%= link_to "See all following", following_path(@user) %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col l1"></div>
    <div class="col l8 page-content center">
      <div class="row">
        <% @posts.each do |post| %>
          <%= render 'shared/post', post: post %>
        <% end %>
      </div>
    </div>
  </div>